name: Build Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build Flutter App Windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache yq Binary
        id: cache-yq
        uses: actions/cache@v4
        with:
          path: C:\ProgramData\chocolatey\lib\yq
          key: ${{ runner.os }}-yq-cache

      - name: Cache Pub Dependencies
        id: cache-pub
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\runneradmin\AppData\Local\Pub\Cache
            .dart_tool
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-cache

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Install Dependencies
        if: steps.cache-pub.outputs.cache-hit != 'true'
        run: flutter pub get

      - name: Build for Windows
        run: flutter build windows --release

      - name: Upload Build Files
        uses: actions/upload-artifact@v4
        with:
          name: AndroidSideloaderWindowsBuild
          path: build/windows/x64/runner/Release/
