name: Build Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build Flutter App Windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build for Windows
        run: flutter build windows

      - name: Get release version
        id: get-release-version
        run: |
          $releaseVersion = yq '.version' pubspec.yaml
          echo "releaseVersion=$releaseVersion" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: installer.iss
          options:  /O+ /DMyAppVersion="${{ env.release-version }}"

      - name: Upload Build Files
        uses: actions/upload-artifact@v4
        with:
          name: AndroidSideloader-${{ env.release-version }}-Windows-Portable
          path: build/windows/x64/runner/Release/
