on:
  push:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write
    name: Build Flutter App macOS
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Define Artifact Paths
        id: define-artifact-paths
        run: |
          ARTIFACT_DIR=build/macos/Build/Products/Release
          ARCHIVE_NAME="${{ github.ref_name }}-macOS.zip"
          echo "ARTIFACT_DIR=$ARTIFACT_DIR" >> $GITHUB_ENV
          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build macOS App
        run: flutter build macos --release --universal

      - name: Upload Build Files
        uses: actions/upload-artifact@v4
        with:
          name: "Android Sideloader.app"
          path: "build/macos/Build/Products/Release/Android Sideloader.app"
