name: Build Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build Flutter App Windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Install Dependencies
        run: flutter pub get

      - name: Build for Windows
        run: flutter build windows --release

      - name: Upload Build Files
        uses: actions/upload-artifact@v4
        with:
          name: AndroidSideloaderWindowsBuild
          path: build/windows/x64/runner/Release/
