name: Build Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    name: Build Flutter App Windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Define Artifact Paths
        id: define-artifact-paths
        run: |
          $archive="build/windows/x64/runner/Release/"
          $installer="build/windows/x64/runner/Installer/Android Sideloader-${{ github.ref_name }}-Windows-Installer.exe"
          echo "ARCHIVE_PATH=$archive" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "INSTALLER_PATH=$installer" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Extract Release Notes
        id: extract_changelog
        run: |
          $ReleaseNotes = & "scripts/get-release-notes.ps1" -VersionName ${{ github.ref_name }}
          if ($LASTEXITCODE -ne 0) {
            Write-Output "$ReleaseNotes"
            exit 1
          }
          echo "RELEASE_NOTES=$ReleaseNotes" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build for Windows
        run: flutter build windows

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: installer.iss
          options:  /O+ /DMyAppVersion="${{ github.ref_name }}"

      - name: Upload Build Files
        uses: actions/upload-artifact@v4
        with:
          name: AndroidSideloader-${{ github.ref_name }}-Windows-Portable
          path: ${{ env.ARCHIVE_PATH }}

      - name: Upload Installer Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AndroidSideloader-${{ github.ref_name }}-Windows-Installer.exe
          path: ${{ env.INSTALLER_PATH }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ env.RELEASE_NOTES }}
          replacesArtifacts: true
          draft: true
          prerelease: true
          artifacts: "${{ env.ARCHIVE_PATH }},${{ env.INSTALLER_PATH }}"
